[TS] parse cover xml

diff --git a/scripts/parse-coverage b/scripts/parse-coverage
--- a/scripts/parse-coverage
+++ b/scripts/parse-coverage
@@ -7,9 +7,10 @@ PERCENT_FLOAT=$(echo "$covered $statements" | awk '{print $1/$2}')
 PERCENT=$(echo "$PERCENT_FLOAT 100" | awk '{printf("%.00f", $1*$2)}')
 THRESHOLD=80
 
-echo $PERCENT
-echo $THRESHOLD
-
-pr=$(echo "$PERCENT $THRESHOLD" | awk 'BEGIN { print ($1 >= $2) ? "YES" : "NO" }')
-
-echo $pr
+if [[ $PERCENT -ge $THRESHOLD ]]; then
+  echo "Test coverage passed"
+  exit 0
+else
+  echo "Test coverage failed"
+  exit 1
+fi
